# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170202_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Topic',
        ),
    ]
